name: complete
version: 1.0.0
description: A complete example of a pubspec file.
homepage: https://github.com/dart-lang/pub-spec
repository: https://github.com/dart-lang/pub-spec
issue_tracker: https://github.com/dart-lang/pub-spec/issues
documentation: https://dart.dev/tools/pub/pubspec
publish_to: https://pub.dev

funding:
  - https://dart.dev/tools/pub/funding

false_secrets:
  - test/foo/secrets.json

screenshots:
  - description: A screenshot of the package.
    path: screenshot.png

topics:
  - pub
  - package

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  version: ^1.15.0
  kittens:
    git: git@github.com:munificent/kittens.git
  some_git:
    git:
      url: https://github.com/dart-lang/some_git.git
      ref: main
      path: ../some_git
  some_git2:
    git:
      url: https://github.com/dart-lang/some_git2.git
      ref: issues/123-test
      path: some_git2
  some_hosted:
    hosted: https://pub.dev
    version: ^1.0.0+1
  some_path:
    path: ../some_path
  some_sdk:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.10.0

executables:
  some_executable: main
  another_executable: another

platforms:
  linux:
  macos:
  windows:

ignored_advisories:
  - GHSA-4rgh-jx4f-qfcq
